[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
wasm-logger = "0.2.0"
log = "0.4.22"
gloo-net = { version = "0.5", features = ["json"] }
futures = "0.3.30"
leptos = { version = "0.6.13", features = ["csr"] }
anyhow = "1.0.86"