name: Build

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - name: Install deps
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Build backend
        run: |
          make -B
