name: Build

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install deps
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install trunk
      - name: Build front-end
        working-directory: ./ui
        run: |
          trunk build --dist ../backend/dist
      - name: Build backend
        working-directory: ./backend
        run: |
          cargo build --release